addIngredient("freshly_scooped_dirt",{
    type:"spice",
    color:"#A07E71",
    keywords:"dirt,sand,earth",
});
addIngredient("feather",{
    type:"cress",
    color:"#ffffff",
    keywords:"bird,feather",
});
addIngredient("hydroxyzine",{
    type:"candy",
    color:"#5599CC",
    keywords:"hydroxyzine,drug,pill,meds,zoloft",
});
addIngredient("toothpaste",{
    type:"cress",
    color:"#26f7fd",
    keywords:"tooth,toothpaste",
});
addIngredient("microplastics",{
    type:"spice",
    color:"#676666",
    keywords:"plastic,microplastic",
});
addIngredient("cum",{
    type:"oil",
    color:"#EEEEEE",
    keywords:"cum,milk,illegal,ejaculate,liquid,semen,jizz,nut",
});
addIngredient("tooth",{
    type:"mutton",
    color:"#EFEFEE",
    keywords:"tooth,illegal",
});
addIngredient("poison",{
    type:"oil",
    color:"#33CC11",
    keywords:"poison,illegal,liquid",
});
addIngredient("blood",{
    type:"oil",
    color:"#990000",
    keywords:"blood,illegal,liquid",
});
addIngredient("infant",{
    type:"r74n",
    color:"#FFD5C4",
    keywords:"child,illegal,doll,human",
});
addIngredient("child",{
    type:"r74n",
    color:"#FF6A00",
    keywords:"child,illegal,doll,human",
});
addIngredient("medicine",{
    type:"candy",
    color:"#CC0000",
    keywords:"drug,illegal,substance",
});
addIngredient("Nondescript_Green_Object",{
    type:"cheeseball",
    color:"#44FF44",
    keywords:"Green, Object
});
